# Needed for CMAKE_MSVC_RUNTIME_LIBRARY
cmake_policy(SET CMP0091 NEW)

if(NOT DEFINED CMAKE_MSVC_RUNTIME_LIBRARY)
  set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>" CACHE STRING "")
  set_property(CACHE CMAKE_MSVC_RUNTIME_LIBRARY PROPERTY STRINGS
    MultiThreaded MultiThreadedDebug MultiThreadedDLL MultiThreadedDebugDLL
  )
endif()

if(NOT DEFINED BUILD_SHARED_LIBS)
  set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build shared libraries")
endif()

if(NOT DEFINED CMAKE_CONFIGURATION_TYPES)
  set(CMAKE_CONFIGURATION_TYPES "Debug;RelWithDebInfo;Release;MinSizeRel" CACHE STRING "")
endif()

if(NOT DEFINED IBAPI_WIN32_WINNT)
  set(IBAPI_WIN32_WINNT 0x0A00 CACHE STRING "Target _WIN32_WINNT")
endif()

if(NOT DEFINED IBAPI_NTDDI_VERSION)
  set(IBAPI_NTDDI_VERSION 0x0A000000 CACHE STRING "Target _NTDDI_VERSION")
endif()

if(NOT DEFINED CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 20 CACHE STRING "C++ standard")
  set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "")
  set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "")
endif()
