if(NOT DEFINED BUILD_SHARED_LIBS)
  set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build shared libraries")
endif()

if(NOT DEFINED FETCHCONTENT_BASE_DIR)
  set(FETCHCONTENT_BASE_DIR "${CMAKE_BINARY_DIR}/_deps" CACHE PATH "FetchContent base dir")
endif()

if(NOT DEFINED CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 20 CACHE STRING "C++ standard")
  set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "")
  set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "")
endif()

# find_program(CMAKE_C_COMPILER_LAUNCHER ccache)
# find_program(CMAKE_CXX_COMPILER_LAUNCHER ccache)
